# Generated by Django 2.2.4 on 2019-08-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscribers1',
        ),
    ]
