# Generated by Django 2.2.4 on 2019-08-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190802_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers1',
            new_name='Subscriber',
        ),
    ]
