# Generated by Django 2.2.4 on 2019-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190802_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_value', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
