# Generated by Django 2.2.4 on 2019-08-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='name',
        ),
        migrations.AddField(
            model_name='rule',
            name='chain',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='rule',
            name='ipv',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rule',
            name='priority',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='rule',
            name='table',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_value',
            field=models.CharField(default='', max_length=256),
        ),
    ]
