# Generated by Django 2.2.4 on 2019-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20190806_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_value',
            field=models.CharField(default='', max_length=256),
        ),
    ]
