# Generated by Django 2.2.4 on 2019-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20190806_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='OUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('ip', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
