# Generated by Django 2.2.4 on 2019-08-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_ouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
