# Generated by Django 2.2.4 on 2019-09-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_delete_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=256)),
                ('r_ip', models.CharField(default='', max_length=256)),
                ('v_ip', models.CharField(default='', max_length=256)),
                ('online_since', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
