# Generated by Django 2.2.4 on 2020-02-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_onlineuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='chain',
            field=models.CharField(choices=[('FORWARD', 'FORWARD'), ('POSTROUTING', 'POSTROUTING')], default='FORWARD', max_length=256),
        ),
        migrations.AlterField(
            model_name='rule',
            name='ipv',
            field=models.CharField(choices=[('ipv4', 'ipv4')], default='ipv4', max_length=64),
        ),
        migrations.AlterField(
            model_name='rule',
            name='priority',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=256),
        ),
        migrations.AlterField(
            model_name='rule',
            name='table',
            field=models.CharField(choices=[('filter', 'filter'), ('nat', 'nat')], default='filter', max_length=256),
        ),
    ]
